# Generated by Django 5.1.3 on 2024-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(error_messages={'unique': 'A user with that user_id already exists.'}, unique=True),
        ),
    ]
