# Generated by Django 5.1.3 on 2024-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_theme',
            field=models.BooleanField(blank=True, default=True, verbose_name='Темная тема'),
        ),
    ]
