# Generated by Django 5.1.3 on 2024-12-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_theme',
        ),
    ]
