# Generated by Django 5.1.3 on 2024-11-21 22:38

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания аукциона')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания аукциона')),
                ('active', models.BooleanField(default=True, verbose_name='Активен ли аукцион')),
                ('max_members', models.PositiveSmallIntegerField(default=20, verbose_name='Кол-во игроков')),
                ('common_bank', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общий банк')),
                ('bet_time', models.PositiveSmallIntegerField(verbose_name='Время на начало/перебив ставки')),
                ('min_bet', models.PositiveIntegerField(verbose_name='Минимальная ставка')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_leader', to=settings.AUTH_USER_MODEL, verbose_name='Победитель аукциона')),
                ('members', models.ManyToManyField(related_name='auctions_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Сумма ставки')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
