# Generated by Django 5.1.3 on 2024-11-23 15:12

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_auction_common_bank_alter_auction_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='leader',
        ),
        migrations.AlterField(
            model_name='auction',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
        migrations.AlterField(
            model_name='auctionbet',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='auction.auction'),
        ),
    ]
