# Generated by Django 5.1.3 on 2024-11-23 18:10

import django.core.validators
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_auction_end_time_remove_auction_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='min_bet',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальная ставка'),
        ),
        migrations.AlterField(
            model_name='auctionbet',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма ставки'),
        ),
    ]
