# Generated by Django 5.1.3 on 2024-11-27 07:46

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws')),
                ('format', models.CharField(choices=[('3x3', '3x3'), ('5x5', '5x5'), ('8x8', '8x8')], max_length=3, verbose_name='Формат карты')),
                ('bet', models.PositiveSmallIntegerField(default=5, verbose_name='Ставка')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало игры')),
                ('map', models.JSONField(verbose_name='Игровое поле')),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_firstplayer', to=settings.AUTH_USER_MODEL, verbose_name='Игрок `X`')),
                ('second_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_secondplayer', to=settings.AUTH_USER_MODEL, verbose_name='Игрок `O`')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_winner', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
        ),
    ]
