# Generated by Django 5.1.3 on 2024-12-01 06:36

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='format',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('8', '8')], max_length=1, verbose_name='Формат карты'),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
    ]
