# Generated by Django 5.1.3 on 2024-12-01 16:16

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoes', '0002_alter_tictactoe_format_alter_tictactoe_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
    ]
