# Generated by Django 5.1.3 on 2024-11-23 18:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балланс кошелька')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец кошелька')),
            ],
        ),
        migrations.CreateModel(
            name='BallanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Сумма транзакции')),
                ('description', models.CharField(max_length=128, verbose_name='Описание')),
                ('ballance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ballance.userwallet')),
            ],
        ),
    ]
