# Generated by Django 5.1.3 on 2024-11-23 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballancetransaction',
            name='ballance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ballance.userwallet'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='ballance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, verbose_name='Балланс кошелька'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Владелец кошелька'),
        ),
    ]
