# Generated by Django 5.1.3 on 2024-12-01 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballance', '0002_alter_ballancetransaction_ballance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballancetransaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата транзакции'),
            preserve_default=False,
        ),
    ]
