# Generated by Django 5.1.3 on 2024-12-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballance', '0003_ballancetransaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballancetransaction',
            name='title',
            field=models.CharField(default=None, max_length=32, verbose_name='Оглавление'),
            preserve_default=False,
        ),
    ]
