# Generated by Django 5.1.3 on 2024-12-02 17:41

import django.core.validators
import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания аукциона')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активен ли джекпот')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
        ),
        migrations.CreateModel(
            name='JackpotBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма ставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpot_bets', to=settings.AUTH_USER_MODEL)),
                ('jackpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='jackpots.jackpots')),
            ],
        ),
    ]
