# Generated by Django 5.1.3 on 2024-12-02 18:08

import django.core.validators
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpotbet',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Сумма ставки'),
        ),
        migrations.AlterField(
            model_name='jackpots',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
    ]
