# Generated by Django 5.1.3 on 2024-12-04 05:32

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpots', '0002_alter_jackpotbet_deposit_alter_jackpots_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackpots',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=64, unique=True, verbose_name='Имя для группы ws'),
        ),
    ]
